### ISSUE TITLE
Update webstore for Chrome v69

### ISSUE THREAD

**Issue by ascendbruce** [Fiddle-N/material-classic-blue-theme#1]
Hi @Fiddle-N, thank you for making awesome themes for Chrome!

I saw the update for Material Incognito Dark. Do you consider releasing a new version for Material Classic Blue as well?

**Comment by ascendbruce** [comment]
Hi @Fiddle-N, I just proposed a PR at https://github.com/Fiddle-N/material-classic-blue-theme/pull/2

**Comment by Fiddle-N** [comment]
Completed. Alea iacta est !
